### ISSUE TITLE
Leading whitespace should not be stripped from interpolated components

### ISSUE THREAD

**Issue by wchargin** [dmnd/dedent#22] opened 2018-07-27 18:46 UTC
As currently written, this module performs interpolation before
stripping leading whitespace. In particular, whitespace is stripped from
the interpolated components. I think that this is the wrong behavior.

My understanding is that `dedent` is supposed to be effectively
syntactic sugar. Writing

```js
function foo() {
  const things = dedent`\
    lorem ipsum
    dolor sit amet
  `;
  return things;
}
```

should be completely equivalent to writing

```js
function foo() {
  const things = `\
lorem ipsum
dolor sit amet
`;
  return things;
}
```

with the sole benefit that the code indentation doesn’t have to become
wonky just to accommodate the text.

This suggests that

```js
function foo() {
  const stuff = "abc\n    xyz";
  const things = dedent`\
    lorem ${stuff}
    dolor sit amet
  `;
  return things;
}
```

should also be equivalent to

```js
function foo() {
  const stuff = "abc\n    xyz";
  const things = `\
lorem ${stuff}
dolor sit amet
`;
  return things;
}
```

which means that the output should be

```
lorem abc
    xyz
dolor sit amet

```

but with the current version of `dedent` the result is actually

```
lorem abc
xyz
dolor sit amet
```

Let me provide a concrete case where this matters. I was using `dedent`
to server-side render static pages on my site. The code looked roughly
like this:

```js
            // lots of context, so this code is indented a bunch...
            const page = dedent`\
                <!DOCTYPE html>
                <html>
                <body>
                <div id="container">${html}</div>
                <script src="${pathToBundle}"></script>
                </body>
                </html>
                `;
```

This all worked well—I wrote it and forgot about it. But when I added
code blocks to my site, I noticed that they rendered incorrectly: code
like

```html
<pre><code>function foo(bar, baz) {
    while (true) {
        if (bar()) {
            console.log("stuff");
            if (baz()) {
                console.log(
                    "even more stuff"
                );
            }
        }
    }
}</code></pre>
```

was being rendered as

```html
<pre><code>function foo(bar, baz) {
while (true) {
if (bar()) {
console.log("stuff");
if (baz()) {
console.log(
    "even more stuff"
);
}
}
}
}</code></pre>
```

in the static HTML. Because `pre` sets `white-space: pre`, the resulting
code is rendered incorrectly in the browser, too. This was somewhat
difficult to track down!

I ended up replacing this module with a hand-written version that fit my
purposes better. (There was an additional change that I needed to make
to properly render code blocks with line-trailing backslashes.) You can
see that change here:

https://github.com/wchargin/wchargin.github.io/commit/06475d4cc44a0437c911dd2d4d6275be4381142e

Is this something that you’re interested in pulling upstream? I realize
that it is a breaking change, so I’d understand if you’re not
interested.

(Also, :wave: !)

**Comment by brandonkal** [comment] 2020-01-11 07:56
Note that your function fails some tests:
```js
it("should do nothing for escaped newlines in template tag", () => {
  const text = dedent`${"one "}\
    two
    three
  `;
  assertEquals(text, "one two\nthree\n");
});
```
The indent on the second line is never removed. Also the first line isn't handled specially.

**Comment by JoshuaKGoldberg** [comment] 2023-05-22 02:33
Hmm, I can see why you'd want this behavior... but also it's a bit counter-intuitive to how the package is positioned right now. Today, it's used as a _"dedent everything in this string"_ utility - not a _"dedent this string, and still allow indents in come contents"_.

Perhaps this can become an opt-in? A couple of API starting ideas..

```js
dedent.recursive`
  ${text}
`;

dedent({ recursive: true })`
  ${text}
`;
```

Thoughts, everyone?

**Comment by JoshuaKGoldberg** [comment] 2023-05-22 02:38
I think this is actually a duplicate of #12. Moving discussion there. Please let me know if that's wrong though!

**Closed by JoshuaKGoldberg** 2023-05-22 02:38 UTC
Labels: status: duplicate
